# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='eid',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photo',
            name='pid',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
