# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Image_File',
            field=models.ImageField(null=True, upload_to='/category/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Image_File',
            field=models.ImageField(upload_to='/image/%Y/%m/%d'),
        ),
    ]
